version: '3.9'

services:
  db:
    image: postgres:16
    container_name: barber_postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - barber_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: barber_app
    command: sh -c "npx prisma migrate deploy && npm run dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"   # API da aplicação
      - "5555:5555"   # Prisma Studio
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}

volumes:
  barber_data:
